### ISSUE TITLE
👆🏼 Nombres de agentes cliceables como botones en módulo de relaciones 

### ISSUE THREAD

**Issue by Juliansintilde** [enflujo/070-lam#33]
Así como al hacer clic en cualquiera de los agentes en la visualización me permite seleccionarlo, sería chévere si que cuando se despliega el módulo de relaciones, al hacer clic en el nombre del agente, se pueda seleccionar.

**Comment by 1cgonza** [comment]
resuelto en [2345ca5](https://github.com/enflujo/070-lam/commit/2345ca5b75dc89f14a28a96565727e182cddda45)
